# Dependencies
markdown:         kramdown
rouge:         true

# Permalinks
permalink:        pretty

# Setup
title:            Samuel Evans
tagline:          'evolutionary biologist'
description:      'Evolutionary Biology PhD Student at the University of British Columbia' 
url:              http://scevans.github.io

author:
  name:           'Samuel Evans'
  url:            https://twitter.com/sc_evans

# paginate:         5

github:
  repo:           https://github.com/scevans/scevans.github.io
