# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Samuel Evans
tagline:          'evolutionary biologist'
description:      'PhD Student at the University of British Columbia <a href="https://twitter.com/sc_evans" target="_blank">@sc_evans</a>' 
url:              http://mwpennell.github.io

author:
  name:           'Samuel Evans'
  url:            https://twitter.com/sc_evans

# paginate:         5

github:
  repo:           https://github.com/scevans/scevans.github.io
